auth:
    resource:
        path: ../src/Auth/Controller/
        namespace: App\Auth\Controller
    type: attribute
    prefix: /api/v1/auth

shop:
    resource:
        path: ../src/Shop/Controller/
        namespace: App\Shop\Controller
    type: attribute
    prefix: /api/v1/shops

client:
    resource:
        path: ../src/Client/Controller/
        namespace: App\Client\Controller
    type: attribute
    prefix: /api/v1/clients

appointment:
    resource:
        path: ../src/Appointment/Controller/
        namespace: App\Appointment\Controller
    type: attribute
    prefix: /api/v1/appointments
    exclude: ../src/Appointment/Controller/PublicAvailableSlotsController.php

reminder:
    resource:
        path: ../src/Reminder/Controller/
        namespace: App\Reminder\Controller
    type: attribute
    prefix: /api/v1/reminders

public_available_slots:
    resource: App\Appointment\Controller\PublicAvailableSlotsController
    type: attribute
    prefix: /api/v1/public/shops