auth:
    resource:
        path: ../src/Auth/Controller/
        namespace: App\Auth\Controller
    type: attribute
    prefix: /api/v1/auth

shop:
    resource:
        path: ../src/Shop/Controller/
        namespace: App\Shop\Controller
    type: attribute
    prefix: /api/v1/shops

client:
    resource:
        path: ../src/Client/Controller/
        namespace: App\Client\Controller
    type: attribute
    prefix: /api/v1/clients