auth:
    resource:
        path: ../src/Auth/Controller/
        namespace: App\Auth\Controller
    type: attribute
    prefix: /api/v1/auth

shop:
    resource:
        path: ../src/Shop/Controller/
        namespace: App\Shop\Controller
    type: attribute
    prefix: /api/v1/shops

client:
    resource:
        path: ../src/Client/Controller/
        namespace: App\Client\Controller
    type: attribute
    prefix: /api/v1/clients

appointment:
    resource:
        path: ../src/Appointment/Controller/
        namespace: App\Appointment\Controller
    type: attribute
    prefix: /api/v1/appointments
    exclude: ../src/Appointment/Controller/PublicAvailableSlotsController.php

subscription:
    resource: App\Subscription\Controller\GetSubscriptionController
    type: attribute
    prefix: /api/v1/subscription

admin_activate:
    resource: App\Subscription\Controller\AdminActivateSubscriptionController
    type: attribute
    prefix: /api/v1/admin

admin_cancel:
    resource: App\Subscription\Controller\AdminCancelSubscriptionController
    type: attribute
    prefix: /api/v1/admin

admin_downgrade:
    resource: App\Subscription\Controller\AdminDowngradeSubscriptionController
    type: attribute
    prefix: /api/v1/admin

public_available_slots:
    resource: App\Appointment\Controller\PublicAvailableSlotsController
    type: attribute
    prefix: /api/v1/public/shops